/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skoleprosjekt;

import Kode.Database;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;



/**
 *
 * @author Sondre
 */
public class Administrator extends javax.swing.JFrame {
    private int ID;
    private String NAVN;
    private String brukernavn;
    private ResultSet res;
    private Database db = new Database();

    /**
     * Creates new form Administrator
     */
    public Administrator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        regUserFrame = new javax.swing.JFrame();
        nameInputField = new javax.swing.JTextField();
        usernameInputField = new javax.swing.JTextField();
        pwInputField = new javax.swing.JTextField();
        phoneInputField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        emailInputField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        chooseUserComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFrame2 = new javax.swing.JFrame();
        jTextField8 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel10 = new javax.swing.JLabel();
        jFrame3 = new javax.swing.JFrame();
        UserName = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        UsernameTextField = new javax.swing.JTextField();
        PasswordTextField = new javax.swing.JTextField();
        PhonenumberTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        EditName = new javax.swing.JButton();
        EditUsername = new javax.swing.JButton();
        EditPassword = new javax.swing.JButton();
        EditPhonenumber = new javax.swing.JButton();
        EditEmail = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        regUserButton = new javax.swing.JButton();
        editUserButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        regUserFrame.setTitle("Register New User");
        regUserFrame.setMinimumSize(new java.awt.Dimension(200, 420));
        regUserFrame.setResizable(false);

        usernameInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameInputFieldActionPerformed(evt);
            }
        });

        phoneInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneInputFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Name");

        jLabel5.setText("Username");

        jLabel7.setText("Password");

        jLabel8.setText("Phonenumber");

        jLabel9.setText("Email");

        submitButton.setBackground(new java.awt.Color(51, 204, 0));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        chooseUserComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose user", "centremanager", "storeowner", "serviceworker" }));
        chooseUserComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseUserComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout regUserFrameLayout = new javax.swing.GroupLayout(regUserFrame.getContentPane());
        regUserFrame.getContentPane().setLayout(regUserFrameLayout);
        regUserFrameLayout.setHorizontalGroup(
            regUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regUserFrameLayout.createSequentialGroup()
                .addGroup(regUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(regUserFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(regUserFrameLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(regUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(regUserFrameLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chooseUserComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(nameInputField)
                            .addComponent(usernameInputField)
                            .addComponent(pwInputField)
                            .addComponent(phoneInputField)))
                    .addGroup(regUserFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(emailInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(regUserFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(submitButton)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        regUserFrameLayout.setVerticalGroup(
            regUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regUserFrameLayout.createSequentialGroup()
                .addGroup(regUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(regUserFrameLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel4)
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regUserFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chooseUserComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(nameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(usernameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel7)
                .addGap(6, 6, 6)
                .addComponent(pwInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addComponent(phoneInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitButton)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jLabel2.setText("jLabel2");

        jLabel6.setText("jLabel6");

        jFrame2.setMinimumSize(new java.awt.Dimension(525, 384));
        jFrame2.setResizable(false);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All Users" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jList1.setMinimumSize(new java.awt.Dimension(525, 384));
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                brukerValgt(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Edit Existing User");

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jFrame2Layout.createSequentialGroup()
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, 0, 122, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(8, 8, 8)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jTextField8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );

        jFrame3.setMinimumSize(new java.awt.Dimension(315, 400));

        UserName.setText("Brukernavn");

        IDLabel.setText("ID");

        jLabel12.setText("Name");

        jLabel13.setText("Username");

        jLabel14.setText("Password");

        jLabel15.setText("Phonenumber");

        jLabel16.setText("Email");

        NameTextField.setText("jTextField9");

        UsernameTextField.setText("jTextField9");

        PasswordTextField.setText("jTextField9");

        PhonenumberTextField.setText("jTextField9");

        EmailTextField.setText("jTextField9");

        EditName.setBackground(new java.awt.Color(51, 153, 0));
        EditName.setText("Save");
        EditName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditNameActionPerformed(evt);
            }
        });

        EditUsername.setBackground(new java.awt.Color(51, 153, 0));
        EditUsername.setText("Save");
        EditUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditUsernameActionPerformed(evt);
            }
        });

        EditPassword.setBackground(new java.awt.Color(51, 153, 0));
        EditPassword.setText("Save");
        EditPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPasswordActionPerformed(evt);
            }
        });

        EditPhonenumber.setBackground(new java.awt.Color(51, 153, 0));
        EditPhonenumber.setText("Save");
        EditPhonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPhonenumberActionPerformed(evt);
            }
        });

        EditEmail.setBackground(new java.awt.Color(51, 153, 0));
        EditEmail.setText("Save");
        EditEmail.setMinimumSize(new java.awt.Dimension(320, 400));
        EditEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame3Layout.createSequentialGroup()
                        .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jFrame3Layout.createSequentialGroup()
                        .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame3Layout.createSequentialGroup()
                                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UserName)
                                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EmailTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EditUsername)
                                    .addComponent(EditName)
                                    .addComponent(EditEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jFrame3Layout.createSequentialGroup()
                                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PhonenumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EditPassword)
                                    .addComponent(EditPhonenumber)))
                            .addComponent(IDLabel))
                        .addContainerGap(14, Short.MAX_VALUE))))
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserName)
                .addGap(18, 18, 18)
                .addComponent(IDLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhonenumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditPhonenumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Users");

        regUserButton.setText("Register New User");
        regUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regUserButtonActionPerformed(evt);
            }
        });

        editUserButton.setText("Edit Existing User");
        editUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Manage Users");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regUserButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editUserButton)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regUserButton)
                    .addComponent(editUserButton))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regUserButtonActionPerformed
        regUserFrame.setVisible(true);
       
    }//GEN-LAST:event_regUserButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void phoneInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneInputFieldActionPerformed

    private void usernameInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameInputFieldActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
       sorterEtterSøk();
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void editUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserButtonActionPerformed
        jFrame2.setVisible(true);
        fyllBrukere();
        fyllYrke();
    }//GEN-LAST:event_editUserButtonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
         sorterEtterYrker();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void chooseUserComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseUserComboBoxActionPerformed
        
    }//GEN-LAST:event_chooseUserComboBoxActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        addUser();
    }//GEN-LAST:event_submitButtonActionPerformed

    private void brukerValgt(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_brukerValgt
        if (!evt.getValueIsAdjusting()) {
            brukernavn = jList1.getSelectedValue().toString();
            jFrame3.setVisible(true);
            UserName.setText(brukernavn);
            fyllEksisterendeBruker();
                     
            //jList1.getSelectedValue().toString();
        }
    }//GEN-LAST:event_brukerValgt

    private void EditNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditNameActionPerformed
        String nr = ""+ID;
        char id = nr.charAt(0);
        int id1 = Character.getNumericValue(id);
        int id2 = ID;
        String user = UsernameTextField.getText();
        String pass = PasswordTextField.getText();
        String name1 = NameTextField.getText();
        int phone = Integer.parseInt(PhonenumberTextField.getText());
        String mail = EmailTextField.getText();
        String userType = "";
        try{
            
            Statement setning = db.kobleTil().createStatement();
            if(id1 == 1) userType = "Update centremanager set centremanager_name = '"+ name1 +"' where centremanager_name = '"+NAVN+"'  ";
            if(id1 == 2) userType = "Update storeowner set owner_name = '"+name1+"' where owner_name = '"+NAVN+"' ";
            if(id1 == 3) userType = "Update serviceworker set serviceworker_name = "+name1+" where serviceworker_name = '"+NAVN+"'";
            
            System.out.println(userType);
            setning.executeUpdate(userType);
            NAVN = name1;
            UserName.setText(name1);
            
            db.kobleFra();  
        }catch(Exception e){
            System.out.println(e);
            db.kobleFra();
        }
    
    }//GEN-LAST:event_EditNameActionPerformed

    private void EditUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditUsernameActionPerformed
        String nr = ""+ID;
        char id = nr.charAt(0);
        System.out.println(ID);
        System.out.println(id);
        int id1 = Character.getNumericValue(id);
        System.out.println(id);
        int id2 = ID;
        String user = UsernameTextField.getText();
        String pass = PasswordTextField.getText();
        String name1 = NameTextField.getText();
        int phone = Integer.parseInt(PhonenumberTextField.getText());
        String mail = EmailTextField.getText();
        String userType = "";
        try{
            
            Statement setning = db.kobleTil().createStatement();
            if(id1 == 1) userType = "update centremanager set username = '"+ user +"' where centremanager_name = '"+NAVN+"'  ";
            if(id1 == 2) userType = "update storeowner set username = '"+user+"' where owner_name = '"+NAVN+"' ";
            if(id1 == 3) userType = "update serviceworker set username = '"+user+"' where serviceworker_name = '"+NAVN+"'";
            
            System.out.println(userType);
            setning.executeUpdate(userType);
            
            
            db.kobleFra();  
        }catch(Exception e){
            System.out.println(e);
            db.kobleFra();
        }
    }//GEN-LAST:event_EditUsernameActionPerformed

    private void EditPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPasswordActionPerformed
        String nr = ""+ID;
        char id = nr.charAt(0);
        int id1 = Character.getNumericValue(id);
        int id2 = ID;
        String user = UsernameTextField.getText();
        String pass = PasswordTextField.getText();
        String name1 = NameTextField.getText();
        int phone = Integer.parseInt(PhonenumberTextField.getText());
        String mail = EmailTextField.getText();
        String userType = "";
        try{
            
            Statement setning = db.kobleTil().createStatement();
            if(id1 == 1) userType = "Update centremanager set password = '"+ pass +"' where centremanager_name = '"+NAVN+"'  ";
            if(id1 == 2) userType = "Update storeowner set password = '"+pass+"' where owner_name = '"+NAVN+"' ";
            if(id1 == 3) userType = "Update serviceworker set password = '"+pass+"' where serviceworker_name = '"+NAVN+"'";
            
            System.out.println(userType);
            setning.executeUpdate(userType);          
            
            db.kobleFra();  
        }catch(Exception e){
            System.out.println(e);
            db.kobleFra();
        }
    }//GEN-LAST:event_EditPasswordActionPerformed

    private void EditPhonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPhonenumberActionPerformed
        String nr = ""+ID;
        char id = nr.charAt(0);
        int id1 = Character.getNumericValue(id);
        int id2 = ID;
        String user = UsernameTextField.getText();
        String pass = PasswordTextField.getText();
        String name1 = NameTextField.getText();
        int phone = Integer.parseInt(PhonenumberTextField.getText());
        String mail = EmailTextField.getText();
        String userType = "";
        try{
            
            Statement setning = db.kobleTil().createStatement();
            if(id1 == 1) userType = "Update centremanager set phonenumber = "+ phone +" where centremanager_name = '"+NAVN+"'  ";
            if(id1 == 2) userType = "Update storeowner set phonenumber = "+phone+" where owner_name = '"+NAVN+"' ";
            if(id1 == 3) userType = "Update serviceworker set phonenumber = "+phone+" where serviceworker_name = '"+NAVN+"'";
            
            System.out.println(userType);
            setning.executeUpdate(userType);          
            
            db.kobleFra();  
        }catch(Exception e){
            System.out.println(e);
            db.kobleFra();
        }
    }//GEN-LAST:event_EditPhonenumberActionPerformed

    private void EditEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditEmailActionPerformed
        String nr = ""+ID;
        char id = nr.charAt(0);
        int id1 = Character.getNumericValue(id);
        int id2 = ID;
        String user = UsernameTextField.getText();
        String pass = PasswordTextField.getText();
        String name1 = NameTextField.getText();
        int phone = Integer.parseInt(PhonenumberTextField.getText());
        String mail = EmailTextField.getText();
        String userType = "";
        try{
            
            Statement setning = db.kobleTil().createStatement();
            if(id1 == 1) userType = "Update centremanager set email = '"+ mail +"' where centremanager_name = '"+NAVN+"'  ";
            if(id1 == 2) userType = "Update storeowner set email = '"+mail+"' where owner_name = '"+NAVN+"' ";
            if(id1 == 3) userType = "Update serviceworker set email = '"+mail+"' where serviceworker_name = '"+NAVN+"'";
            
            System.out.println(userType);
            setning.executeUpdate(userType);          
            
            db.kobleFra();  
        }catch(Exception e){
            System.out.println(e);
            db.kobleFra();
        }
    }//GEN-LAST:event_EditEmailActionPerformed
    
    public void fyllEksisterendeBruker(){
    try{
            
            Statement setning = db.kobleTil().createStatement();
            db.createView();
            res = setning.executeQuery("select username, password, id, name, phonenumber, email from allebrukere where name = '" + brukernavn + "'");
            res.next();
            ID = Integer.parseInt(res.getString("id"));
            IDLabel.setText("ID: "+res.getString("id"));
            NAVN = res.getString("name");
            UsernameTextField.setText(res.getString("username"));
            PasswordTextField.setText(res.getString("password"));
            NameTextField.setText(res.getString("name"));
            PhonenumberTextField.setText(res.getString("phonenumber"));
            EmailTextField.setText(res.getString("email"));
            db.destroyView();
            db.kobleFra();
        }catch(Exception e){
            System.out.println(e);
            db.kobleFra();
        }
    }
    
    private void addUser(){
        
        String userType ="";       
        String userType2 = "";
        String id2 = "";
        String make = "";
        String name = nameInputField.getText();
        String username = usernameInputField.getText();
        String password = pwInputField.getText();
        int phonenumber = Integer.parseInt(phoneInputField.getText());
        String email = emailInputField.getText();
        int a = chooseUserComboBox.getSelectedIndex();
        
        
        try {
            
            Statement setning = db.kobleTil().createStatement();                                   
            
            if(a == 1) 
            userType = "centremanager(centremanager_name";
            make = "shoppingcentre";
            if(a == 2) 
            userType = "storeowner (owner_name";         
            if(a == 3) 
            userType = "serviceworker(serviceworker_name";
            
                       
            String insert = "insert into "+userType+",USERNAME,PASSWORD,PHONENUMBER,EMAIL) VALUES( '" + name + "', '" + username + "', '" + password + "', " +phonenumber + ", '" +email +"')";
            setning.executeUpdate(insert);          
                                      
            db.kobleFra();
        }catch(Exception e){
            System.out.println("Feil med addUser del 1 " + e);
            db.kobleFra();
        }
        
        try{
            Statement setning = db.kobleTil().createStatement();
            if(make.equals("shoppingcentre")); 
            res = setning.executeQuery("select manager_id from centremanager where centremanager_name = '"+name+"'");
            res.next();
            id2 = res.getString("manager_id");
            userType2 = "insert into shoppingcentre(Manager_ID) values("+id2+")";
            setning.executeUpdate(userType2);
            
           
            db.kobleFra();
        }catch(Exception r){
            System.out.println("Feil med adduser del 2" + r);
            db.kobleFra();
            
        }
    }
    
    private void sorterEtterSøk(){
        try{
            DefaultListModel DLM = new DefaultListModel();
            String søkeOrd = jTextField8.getText();
            Statement setning = db.kobleTil().createStatement();
            db.createView();
            res = setning.executeQuery("select name from allebrukere where upper(name) LIKE upper('"+søkeOrd+"%')");
            while (res.next()) {
                        String navn = res.getString("name");
                        DLM.addElement(navn);
                    }
                    jList1.setModel(DLM);
                    db.destroyView();
                    db.kobleFra();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Her oppsto det en feil" + e + "");
                db.kobleFra();
            }
    }
    
    private void sorterEtterYrker(){
        try{
            Object yrke = jComboBox1.getSelectedItem();
            yrke = yrke.toString();
            Statement setning = db.kobleTil().createStatement();
            db.createView();
            DefaultListModel DLM1 = new DefaultListModel();
            if(yrke.equals("All Users")){
                res = setning.executeQuery("select name from allebrukere");
                while (res.next()) {
                    String navn = res.getString("name");
                    DLM1.addElement(navn);
                }
                jList1.setModel(DLM1);
            }
            
            else if(yrke.equals("CentreManager")){
                res = setning.executeQuery("select centremanager_name from centremanager");
                while (res.next()){
                    String navn = res.getString("centremanager_name");
                    DLM1.addElement(navn);
                }
                jList1.setModel(DLM1);
            }
            else if(yrke.equals("ServiceCenter")){
                res = setning.executeQuery("select serviceworker_name from serviceworker");
                while (res.next()){
                    String navn = res.getString("serviceworker_name");
                    DLM1.addElement(navn);
                }
                jList1.setModel(DLM1);
            }
            else if(yrke.equals("StoreOwner")){
                res = setning.executeQuery("select owner_name from storeowner");
                while (res.next()){
                    String navn = res.getString("owner_name");
                    DLM1.addElement(navn);
                }
                jList1.setModel(DLM1);
            }
            else{
                res = setning.executeQuery("select name from allebrukere");
                while (res.next()) {
                    String navn = res.getString("name");
                    DLM1.addElement(navn);
                }
                jList1.setModel(DLM1);
            }
            db.destroyView();
        db.kobleFra();
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Her oppsto det en feil" + e + "");
            db.kobleFra();
        }
    }
    private void fyllBrukere(){
        try{
            Statement setning = db.kobleTil().createStatement();
            db.createView();
            DefaultListModel DLM = new DefaultListModel();
            res = setning.executeQuery("select name from allebrukere where id between 1000 and 3999");
            while(res.next()){
                String navn = res.getString("name");
                DLM.addElement(navn);
            }
            jList1.setModel(DLM);
            db.destroyView();
            db.kobleFra();
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, "En feil oppstod tilknyttet metoden fyllBrukere" + e + "");
            db.kobleFra();
        }
    }
    
    private void fyllYrke(){
        String[] yrkeliste = {"CentreManager", "ServiceCenter", "StoreOwner"};
        for(int i = 0; i < yrkeliste.length; i++){
            String navn1 = yrkeliste[i];
            jComboBox1.addItem(navn1);
         
            
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void run(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditEmail;
    private javax.swing.JButton EditName;
    private javax.swing.JButton EditPassword;
    private javax.swing.JButton EditPhonenumber;
    private javax.swing.JButton EditUsername;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JTextField PasswordTextField;
    private javax.swing.JTextField PhonenumberTextField;
    private javax.swing.JLabel UserName;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JComboBox chooseUserComboBox;
    private javax.swing.JButton editUserButton;
    private javax.swing.JTextField emailInputField;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField nameInputField;
    private javax.swing.JTextField phoneInputField;
    private javax.swing.JTextField pwInputField;
    private javax.swing.JButton regUserButton;
    private javax.swing.JFrame regUserFrame;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField usernameInputField;
    // End of variables declaration//GEN-END:variables
}
