/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skoleprosjekt;

import Kode.Database;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;



/**
 *
 * @author Sondre
 */
public class Administrator extends javax.swing.JFrame {
    private String brukernavn;
    private ResultSet res;
    private Database db = new Database();

    /**
     * Creates new form Administrator
     */
    public Administrator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jFrame1 = new javax.swing.JFrame();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFrame2 = new javax.swing.JFrame();
        jTextField8 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel10 = new javax.swing.JLabel();
        jFrame3 = new javax.swing.JFrame();
        UserName = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        IDTextField = new javax.swing.JTextField();
        NameTextField = new javax.swing.JTextField();
        UsernameTextField = new javax.swing.JTextField();
        PasswordTextField = new javax.swing.JTextField();
        PhonenumberTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        EditID = new javax.swing.JButton();
        EditName = new javax.swing.JButton();
        EditUsername = new javax.swing.JButton();
        EditPassword = new javax.swing.JButton();
        EditPhonenumber = new javax.swing.JButton();
        EditEmail = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jFrame1.setTitle("Register New User");
        jFrame1.setMinimumSize(new java.awt.Dimension(200, 420));
        jFrame1.setPreferredSize(new java.awt.Dimension(500, 400));
        jFrame1.setResizable(false);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel3.setText("ID");

        jLabel4.setText("Name");

        jLabel5.setText("Username");

        jLabel7.setText("Password");

        jLabel8.setText("Phonenumber");

        jLabel9.setText("Email");

        jButton6.setBackground(new java.awt.Color(51, 204, 0));
        jButton6.setText("Submit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose user", "centremanager", "storeowner", "serviceworker" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jFrame1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jFrame1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel9))
                        .addGroup(jFrame1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jTextField2)
                                .addComponent(jTextField3)
                                .addComponent(jTextField4)
                                .addComponent(jTextField5)
                                .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                        .addGroup(jFrame1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jTextField7)))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton6)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel7)
                .addGap(6, 6, 6)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jLabel2.setText("jLabel2");

        jLabel6.setText("jLabel6");

        jFrame2.setMinimumSize(new java.awt.Dimension(525, 384));
        jFrame2.setResizable(false);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All Users" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jList1.setMinimumSize(new java.awt.Dimension(525, 384));
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                brukerValgt(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Edit Existing User");

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jFrame2Layout.createSequentialGroup()
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, 0, 122, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(8, 8, 8)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jTextField8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );

        UserName.setText("Brukernavn");

        jLabel11.setText("ID");

        jLabel12.setText("Name");

        jLabel13.setText("Username");

        jLabel14.setText("Password");

        jLabel15.setText("Phonenumber");

        jLabel16.setText("Email");

        IDTextField.setText("jTextField9");

        NameTextField.setText("jTextField9");

        UsernameTextField.setText("jTextField9");

        PasswordTextField.setText("jTextField9");

        PhonenumberTextField.setText("jTextField9");

        EmailTextField.setText("jTextField9");

        EditID.setBackground(new java.awt.Color(51, 153, 0));
        EditID.setText("Save");
        EditID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditIDActionPerformed(evt);
            }
        });

        EditName.setBackground(new java.awt.Color(51, 153, 0));
        EditName.setText("Save");
        EditName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditNameActionPerformed(evt);
            }
        });

        EditUsername.setBackground(new java.awt.Color(51, 153, 0));
        EditUsername.setText("Save");
        EditUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditUsernameActionPerformed(evt);
            }
        });

        EditPassword.setBackground(new java.awt.Color(51, 153, 0));
        EditPassword.setText("Save");
        EditPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPasswordActionPerformed(evt);
            }
        });

        EditPhonenumber.setBackground(new java.awt.Color(51, 153, 0));
        EditPhonenumber.setText("Save");
        EditPhonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPhonenumberActionPerformed(evt);
            }
        });

        EditEmail.setBackground(new java.awt.Color(51, 153, 0));
        EditEmail.setText("Save");
        EditEmail.setMinimumSize(new java.awt.Dimension(320, 400));
        EditEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jFrame3Layout.createSequentialGroup()
                        .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame3Layout.createSequentialGroup()
                                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UserName)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel16)
                                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(EditID)
                                        .addComponent(EditName)
                                        .addComponent(EditUsername))
                                    .addComponent(EditEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jFrame3Layout.createSequentialGroup()
                                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PhonenumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EditPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(EditPhonenumber, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(33, 33, 33))))
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserName)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(11, 11, 11)
                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditPassword))
                .addGap(5, 5, 5)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhonenumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditPhonenumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Users");

        jButton2.setText("Register New User");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Edit Existing User");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Manage Users");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jFrame1.setVisible(true);
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
       sorterEtterSøk();
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jFrame2.setVisible(true);
        fyllBrukere();
        fyllYrke();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
         sorterEtterYrker();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        jTextField2.setText("" + jComboBox2.getSelectedIndex());
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        addUser();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void brukerValgt(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_brukerValgt
        if (!evt.getValueIsAdjusting()) {
            brukernavn = jList1.getSelectedValue().toString();
            jFrame3.setVisible(true);
            UserName.setText(brukernavn);
            fyllEksisterendeBruker();
                     
            //jList1.getSelectedValue().toString();
        }
    }//GEN-LAST:event_brukerValgt

    private void EditIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditIDActionPerformed
        char id = IDTextField.getText().charAt(0);
        int id1 = Character.getNumericValue(id);
        int id2 = Integer.parseInt(IDTextField.getText());
        String user = UsernameTextField.getText();
        String pass = PasswordTextField.getText();
        String name1 = NameTextField.getText();
        int phone = Integer.parseInt(PhonenumberTextField.getText());
        String mail = EmailTextField.getText();
        String userType = "";
        try{
            
            Statement setning = db.kobleTil().createStatement();
            if(id1 == 1) userType = "centremanager set MANAGER_ID = "+ id2 +"where centremanager_name = '"+name1+"'  ";
            if(id1 == 2) userType = "storeowner set owner_id = "+id2+" where owner_name = '"+name1+"' ";
            if(id1 == 3) userType = "serviceworker set serviceworker_id = "+id2+" where serviceworker_name = '"+name1+"'";
            
            
            String oppdaterBruker = "update "+userType+")";
            setning.executeUpdate(oppdaterBruker);
            
           
            
            
            db.kobleFra();
            
            
        
            
        }catch(Exception e){
            System.out.println(e);
            db.kobleFra();
        }
    }//GEN-LAST:event_EditIDActionPerformed

    private void EditNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditNameActionPerformed
        char id = IDTextField.getText().charAt(0);
        int id1 = Character.getNumericValue(id);
        int id2 = Integer.parseInt(IDTextField.getText());
        String user = UsernameTextField.getText();
        String pass = PasswordTextField.getText();
        String name1 = NameTextField.getText();
        int phone = Integer.parseInt(PhonenumberTextField.getText());
        String mail = EmailTextField.getText();
        String userType = "";
        try{
            
            Statement setning = db.kobleTil().createStatement();
            if(id1 == 1) userType = "centremanager set centermanager_name = "+ name1 +"where centremanager_name = '"+name1+"'  ";
            if(id1 == 2) userType = "storeowner set owner_name = '"+name1+"' where owner_name = '"+name1+"' ";
            if(id1 == 3) userType = "serviceworker set serviceworker_name = "+name1+" where serviceworker_name = '"+name1+"'";
            
            
            String oppdaterBruker = "update "+userType+"";
            setning.executeUpdate(oppdaterBruker);          
            
            db.kobleFra();  
        }catch(Exception e){
            System.out.println(e);
            db.kobleFra();
        }
    
    }//GEN-LAST:event_EditNameActionPerformed

    private void EditUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditUsernameActionPerformed
        char id = IDTextField.getText().charAt(0);
        int id1 = Character.getNumericValue(id);
        int id2 = Integer.parseInt(IDTextField.getText());
        String user = UsernameTextField.getText();
        String pass = PasswordTextField.getText();
        String name1 = NameTextField.getText();
        int phone = Integer.parseInt(PhonenumberTextField.getText());
        String mail = EmailTextField.getText();
        String userType = "";
        try{
            
            Statement setning = db.kobleTil().createStatement();
            if(id1 == 1) userType = "centremanager set username = '"+ user +"'where centremanager_name = '"+name1+"'  ";
            if(id1 == 2) userType = "storeowner set username = "+user+" where owner_name = '"+name1+"' ";
            if(id1 == 3) userType = "serviceworker set username = '"+user+"' where serviceworker_name = '"+name1+"'";
            
            
            String oppdaterBruker = "update "+userType+"";
            setning.executeUpdate(oppdaterBruker);          
            
            db.kobleFra();  
        }catch(Exception e){
            System.out.println(e);
            db.kobleFra();
        }
    }//GEN-LAST:event_EditUsernameActionPerformed

    private void EditPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPasswordActionPerformed
        char id = IDTextField.getText().charAt(0);
        int id1 = Character.getNumericValue(id);
        int id2 = Integer.parseInt(IDTextField.getText());
        String user = UsernameTextField.getText();
        String pass = PasswordTextField.getText();
        String name1 = NameTextField.getText();
        int phone = Integer.parseInt(PhonenumberTextField.getText());
        String mail = EmailTextField.getText();
        String userType = "";
        try{
            
            Statement setning = db.kobleTil().createStatement();
            if(id1 == 1) userType = "centremanager set password = '"+ pass +"' where centremanager_name = '"+name1+"'  ";
            if(id1 == 2) userType = "storeowner set password = '"+pass+"' where owner_name = '"+name1+"' ";
            if(id1 == 3) userType = "serviceworker set password = '"+pass+"' where serviceworker_name = '"+name1+"'";
            
            
            String oppdaterBruker = "update "+userType+"";
            setning.executeUpdate(oppdaterBruker);          
            
            db.kobleFra();  
        }catch(Exception e){
            System.out.println(e);
            db.kobleFra();
        }
    }//GEN-LAST:event_EditPasswordActionPerformed

    private void EditPhonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPhonenumberActionPerformed
        char id = IDTextField.getText().charAt(0);
        int id1 = Character.getNumericValue(id);
        int id2 = Integer.parseInt(IDTextField.getText());
        String user = UsernameTextField.getText();
        String pass = PasswordTextField.getText();
        String name1 = NameTextField.getText();
        int phone = Integer.parseInt(PhonenumberTextField.getText());
        String mail = EmailTextField.getText();
        String userType = "";
        try{
            
            Statement setning = db.kobleTil().createStatement();
            if(id1 == 1) userType = "centremanager set phonenumber = "+ phone +"where centremanager_name = '"+name1+"'  ";
            if(id1 == 2) userType = "storeowner set phonenumber = "+phone+" where owner_name = '"+name1+"' ";
            if(id1 == 3) userType = "serviceworker set phonenumber = "+phone+" where serviceworker_name = '"+name1+"'";
            
            
            String oppdaterBruker = "update "+userType+"";
            setning.executeUpdate(oppdaterBruker);          
            
            db.kobleFra();  
        }catch(Exception e){
            System.out.println(e);
            db.kobleFra();
        }
    }//GEN-LAST:event_EditPhonenumberActionPerformed

    private void EditEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditEmailActionPerformed
        char id = IDTextField.getText().charAt(0);
        int id1 = Character.getNumericValue(id);
        int id2 = Integer.parseInt(IDTextField.getText());
        String user = UsernameTextField.getText();
        String pass = PasswordTextField.getText();
        String name1 = NameTextField.getText();
        int phone = Integer.parseInt(PhonenumberTextField.getText());
        String mail = EmailTextField.getText();
        String userType = "";
        try{
            
            Statement setning = db.kobleTil().createStatement();
            if(id1 == 1) userType = "centremanager set email = '"+ mail +"' where centremanager_name = '"+name1+"'  ";
            if(id1 == 2) userType = "storeowner set email = '"+mail+"' where owner_name = '"+name1+"' ";
            if(id1 == 3) userType = "serviceworker set email = '"+mail+"' where serviceworker_name = '"+name1+"'";
            
            
            String oppdaterBruker = "update "+userType+"";
            setning.executeUpdate(oppdaterBruker);          
            
            db.kobleFra();  
        }catch(Exception e){
            System.out.println(e);
            db.kobleFra();
        }
    }//GEN-LAST:event_EditEmailActionPerformed
    
    public void fyllEksisterendeBruker(){
    try{
            
            Statement setning = db.kobleTil().createStatement();
            res = setning.executeQuery("select username, password, id, name, phonenumber, email from allebrukere where name = '" + brukernavn + "'");
            res.next();
            IDTextField.setText(res.getString("id"));
            UsernameTextField.setText(res.getString("username"));
            PasswordTextField.setText(res.getString("password"));
            NameTextField.setText(res.getString("name"));
            PhonenumberTextField.setText(res.getString("phonenumber"));
            EmailTextField.setText(res.getString("email"));
            
        }catch(Exception e){
            System.out.println(e);
            db.kobleFra();
        }
    }
    
    private void addUser(){
        try {
            
            Statement setning = db.kobleTil().createStatement();
            int id = Integer.parseInt(jTextField2.getText());
            String name = jTextField3.getText();
            String username = jTextField4.getText();
            String password = jTextField5.getText();
            int phonenumber = Integer.parseInt(jTextField6.getText());
            String email = jTextField7.getText();
            int a = jComboBox2.getSelectedIndex();
            String userType ="";
            if(a == 1) userType = "centremanager(MANAGER_ID, centremanager_name";
            if(a == 2) userType = "storeowner (owner_id, owner_name";
            if(a == 3) userType = "serviceworker(serviceworker_id, serviceworker_name";
            
            
            String insert = "insert into "+userType+",USERNAME,PASSWORD,PHONENUMBER,EMAIL) VALUES(" + id +", '" + name + "', '" + username + "', '" + password + "', " +phonenumber + ", '" +email +"')";
            setning.executeUpdate(insert);
            
           
            
            
            db.kobleFra();
        }catch(SQLException e){
            System.out.println(e);
            db.kobleFra();
        }
    }
    
    private void sorterEtterSøk(){
        try{
            DefaultListModel DLM = new DefaultListModel();
            String søkeOrd = jTextField8.getText();
            Statement setning = db.kobleTil().createStatement();
            res = setning.executeQuery("select name from navn where upper(name) LIKE upper('"+søkeOrd+"%')");
            while (res.next()) {
                        String navn = res.getString("name");
                        DLM.addElement(navn);
                    }
                    jList1.setModel(DLM);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Her oppsto det en feil" + e + "");
                db.kobleFra();
            }
    }
    
    private void sorterEtterYrker(){
        try{
            Object yrke = jComboBox1.getSelectedItem();
            yrke = yrke.toString();
            Statement setning = db.kobleTil().createStatement();
            DefaultListModel DLM1 = new DefaultListModel();
            if(yrke.equals("All Users")){
                res = setning.executeQuery("select name from navn");
                while (res.next()) {
                    String navn = res.getString("name");
                    DLM1.addElement(navn);
                }
                jList1.setModel(DLM1);
            }
            
            else if(yrke.equals("CentreManager")){
                res = setning.executeQuery("select centremanager_name from centremanager");
                while (res.next()){
                    String navn = res.getString("centremanager_name");
                    DLM1.addElement(navn);
                }
                jList1.setModel(DLM1);
            }
            else if(yrke.equals("ServiceCenter")){
                res = setning.executeQuery("select serviceworker_name from serviceworker");
                while (res.next()){
                    String navn = res.getString("serviceworker_name");
                    DLM1.addElement(navn);
                }
                jList1.setModel(DLM1);
            }
            else if(yrke.equals("StoreOwner")){
                res = setning.executeQuery("select owner_name from storeowner");
                while (res.next()){
                    String navn = res.getString("owner_name");
                    DLM1.addElement(navn);
                }
                jList1.setModel(DLM1);
            }
            else{
                res = setning.executeQuery("select name from navn");
                while (res.next()) {
                    String navn = res.getString("name");
                    DLM1.addElement(navn);
                }
                jList1.setModel(DLM1);
            }
        db.kobleFra();
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Her oppsto det en feil" + e + "");
            db.kobleFra();
        }
    }
    private void fyllBrukere(){
        try{
            Statement setning = db.kobleTil().createStatement();
            DefaultListModel DLM = new DefaultListModel();
            res = setning.executeQuery("select name from navn");
            while(res.next()){
                String navn = res.getString("name");
                DLM.addElement(navn);
            }
            jList1.setModel(DLM);
            db.kobleFra();
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, "En feil oppstod tilknyttet metoden fyllBrukere" + e + "");
            db.kobleFra();
        }
    }
    
    private void fyllYrke(){
        String[] yrkeliste = {"CentreManager", "ServiceCenter", "StoreOwner"};
        for(int i = 0; i < yrkeliste.length; i++){
            String navn1 = yrkeliste[i];
            jComboBox1.addItem(navn1);
         
            
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditEmail;
    private javax.swing.JButton EditID;
    private javax.swing.JButton EditName;
    private javax.swing.JButton EditPassword;
    private javax.swing.JButton EditPhonenumber;
    private javax.swing.JButton EditUsername;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JTextField IDTextField;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JTextField PasswordTextField;
    private javax.swing.JTextField PhonenumberTextField;
    private javax.swing.JLabel UserName;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
