/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package skoleprosjekt;

import Kode.Database;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Eirik Saur
 */
public class StoreOwner extends javax.swing.JFrame {
    private String storeName;
    private String username;
    private ResultSet res;
    private ResultSet res1;
    private Database db = new Database();
    private int id;
    private ArrayList<Integer> productIDs = new ArrayList();
    private int chosenProductID;
    
    /**
     * Creates new form StoreOwner
     */
    public StoreOwner(String username) {
        try{
        this.username = username;
        Statement setning = db.kobleTil().createStatement();
        res = setning.executeQuery("select owner_id from storeowner where username = '"+username+"'" );
        res.next();
        id = res.getInt("owner_id");
        
        res = setning.executeQuery("select store_name from store where owner_id = "+id+"");
        
        res.next();
        storeName = res.getString("store_name");
        initComponents();
        fyllProdukt();
        fyllStoreInfo();
        Name.setText("Store need a name");
        endreNavn(storeName);
        db.kobleFra();
        }catch(SQLException e){
              
        }
        db.kobleFra();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editProductWindow = new javax.swing.JFrame();
        productBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        navneFelt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        beskrivelse = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        prisFelt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        antallFelt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        produsentFelt = new javax.swing.JTextField();
        saveProductButton = new javax.swing.JButton();
        editStoreWindow = new javax.swing.JFrame();
        storeBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        storeTypeField = new javax.swing.JTextField();
        turnoverField = new javax.swing.JTextField();
        buildingField = new javax.swing.JTextField();
        floorField = new javax.swing.JTextField();
        storeNameField = new javax.swing.JTextField();
        saveStoreButton = new javax.swing.JButton();
        regProductWindow = new javax.swing.JFrame();
        regProductName = new javax.swing.JTextField();
        productRegBack = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        regProductDescription = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        regProductPrice = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        regProductQuantity = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        regProductManufacturer = new javax.swing.JTextField();
        regButton = new javax.swing.JButton();
        editStoreButton = new javax.swing.JButton();
        editProductButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        productList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        storeInfo = new javax.swing.JTextArea();
        Name = new javax.swing.JLabel();
        deleteProductButton = new javax.swing.JButton();
        regProductButton = new javax.swing.JButton();

        editProductWindow.setTitle("Edit Product Info");
        editProductWindow.setMinimumSize(new java.awt.Dimension(700, 300));

        productBack.setBackground(new java.awt.Color(255, 0, 0));
        productBack.setText("Cancel");
        productBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productBackActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        navneFelt.setText("jTextField1");

        jLabel3.setText("Description");

        beskrivelse.setText("jTextField1");

        jLabel4.setText("Price");

        prisFelt.setText("jTextField1");

        jLabel5.setText("Quantity");

        antallFelt.setText("jTextField1");

        jLabel6.setText("Manufacturer");

        produsentFelt.setText("jTextField1");

        saveProductButton.setText("Save");
        saveProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProductButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editProductWindowLayout = new javax.swing.GroupLayout(editProductWindow.getContentPane());
        editProductWindow.getContentPane().setLayout(editProductWindowLayout);
        editProductWindowLayout.setHorizontalGroup(
            editProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editProductWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editProductWindowLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(editProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(beskrivelse, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(navneFelt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(editProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(editProductWindowLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(antallFelt, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(editProductWindowLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(produsentFelt, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(editProductWindowLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(prisFelt, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(editProductWindowLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(productBack, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(saveProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        editProductWindowLayout.setVerticalGroup(
            editProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editProductWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(navneFelt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(beskrivelse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prisFelt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(antallFelt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(produsentFelt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveProductButton)
                    .addComponent(productBack))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        editStoreWindow.setTitle("Edit Store Info");
        editStoreWindow.setMinimumSize(new java.awt.Dimension(550, 300));

        storeBack.setBackground(new java.awt.Color(255, 0, 0));
        storeBack.setText("Back");
        storeBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeBackActionPerformed(evt);
            }
        });

        jLabel7.setText("Store name");

        jLabel8.setText("Store type");

        jLabel9.setText("Turnover");

        jLabel10.setText("Building");

        jLabel11.setText("Floor");

        storeTypeField.setText("jTextField6");

        turnoverField.setText("jTextField6");

        buildingField.setText("jTextField6");

        floorField.setText("jTextField6");

        storeNameField.setText("jTextField6");

        saveStoreButton.setText("Save");
        saveStoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveStoreButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editStoreWindowLayout = new javax.swing.GroupLayout(editStoreWindow.getContentPane());
        editStoreWindow.getContentPane().setLayout(editStoreWindowLayout);
        editStoreWindowLayout.setHorizontalGroup(
            editStoreWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editStoreWindowLayout.createSequentialGroup()
                .addComponent(storeBack)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(editStoreWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editStoreWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editStoreWindowLayout.createSequentialGroup()
                        .addGroup(editStoreWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addGroup(editStoreWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editStoreWindowLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(storeNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(editStoreWindowLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(editStoreWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(floorField, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buildingField, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(editStoreWindowLayout.createSequentialGroup()
                        .addGroup(editStoreWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(editStoreWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(storeTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(turnoverField, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel11))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editStoreWindowLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveStoreButton)
                .addGap(161, 161, 161))
        );
        editStoreWindowLayout.setVerticalGroup(
            editStoreWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editStoreWindowLayout.createSequentialGroup()
                .addComponent(storeBack)
                .addGap(19, 19, 19)
                .addGroup(editStoreWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(storeNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(editStoreWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(storeTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editStoreWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(turnoverField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(14, 14, 14)
                .addGroup(editStoreWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buildingField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editStoreWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(floorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveStoreButton)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        regProductWindow.setTitle("Register New Product");
        regProductWindow.setMinimumSize(new java.awt.Dimension(450, 350));

        productRegBack.setBackground(new java.awt.Color(255, 0, 0));
        productRegBack.setText("Back");
        productRegBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productRegBackActionPerformed(evt);
            }
        });

        jLabel12.setText("Name");

        jLabel13.setText("Description");

        jLabel14.setText("Price");

        jLabel15.setText("Quantity");

        jLabel16.setText("Manufacturer");

        regButton.setBackground(new java.awt.Color(51, 153, 0));
        regButton.setText("Register");
        regButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout regProductWindowLayout = new javax.swing.GroupLayout(regProductWindow.getContentPane());
        regProductWindow.getContentPane().setLayout(regProductWindowLayout);
        regProductWindowLayout.setHorizontalGroup(
            regProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regProductWindowLayout.createSequentialGroup()
                .addGroup(regProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(regProductWindowLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(productRegBack))
                    .addGroup(regProductWindowLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(regProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(24, 24, 24)
                        .addGroup(regProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(regProductName, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(regProductDescription)
                            .addComponent(regProductPrice)
                            .addComponent(regProductQuantity)
                            .addComponent(regProductManufacturer)
                            .addComponent(regButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        regProductWindowLayout.setVerticalGroup(
            regProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regProductWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productRegBack)
                .addGap(15, 15, 15)
                .addGroup(regProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(regProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(regProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(regProductDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(regProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(regProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(regProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(regProductQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(regProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(regProductManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regButton)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Store Owner");

        editStoreButton.setBackground(new java.awt.Color(0, 204, 0));
        editStoreButton.setText("Edit store info");
        editStoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStoreButtonActionPerformed(evt);
            }
        });

        editProductButton.setText("Edit product");
        editProductButton.setEnabled(false);
        editProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProductButtonActionPerformed(evt);
            }
        });

        productList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        productList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                productSelected(evt);
            }
        });
        jScrollPane1.setViewportView(productList);

        storeInfo.setEditable(false);
        storeInfo.setColumns(20);
        storeInfo.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        storeInfo.setRows(5);
        jScrollPane2.setViewportView(storeInfo);

        Name.setFont(new java.awt.Font("sansserif", 3, 36)); // NOI18N
        Name.setText("NAVN PÅ BUTIKK");

        deleteProductButton.setText("Delete product");
        deleteProductButton.setEnabled(false);
        deleteProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductButtonActionPerformed(evt);
            }
        });

        regProductButton.setBackground(new java.awt.Color(0, 204, 0));
        regProductButton.setText("Reg product");
        regProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regProductButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(editStoreButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(regProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(editProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(deleteProductButton))
                                .addComponent(jScrollPane1)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editStoreButton)
                    .addComponent(regProductButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editProductButton)
                            .addComponent(deleteProductButton))))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editStoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStoreButtonActionPerformed
            editStoreWindow.setVisible(true);
            try{
                storeNameField.setText(storeName);
                Statement setning = db.kobleTil().createStatement();
                res = setning.executeQuery("select store_type from store where owner_id = "+id+"" );
                res.next();
                storeTypeField.setText(res.getString("store_type"));
                res = setning.executeQuery("select turnover from store where owner_id = "+id+"" );
                res.next();
                turnoverField.setText(""+res.getDouble("turnover"));
                res = setning.executeQuery("select building from store where owner_id = "+id+"" );
                res.next();
                buildingField.setText(res.getString("building"));
                res = setning.executeQuery("select floor from store where owner_id = "+id+"" );
                res.next();
                floorField.setText(""+res.getInt("floor"));
                db.kobleFra();
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, "Her oppsto det en feil" + e + "");
                db.kobleFra();
            }
    }//GEN-LAST:event_editStoreButtonActionPerformed

    private void editProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProductButtonActionPerformed
        if(productList.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null,"Du må velge ett produkt fra listen først");
        } 
        else {
            editProductWindow.setVisible(true);
            chosenProductID = productIDs.get(productList.getSelectedIndex());
            try{
                navneFelt.setText(productList.getSelectedValue().toString());
                Statement setning = db.kobleTil().createStatement();
                res = setning.executeQuery("select description from product where product_nr = "+chosenProductID);
                res.next();
                beskrivelse.setText(res.getString("description"));
                res = setning.executeQuery("select price from product where product_nr = "+chosenProductID);
                res.next();
                prisFelt.setText(""+res.getInt("price"));
                res = setning.executeQuery("select quantity from product where product_nr = "+chosenProductID);
                res.next();
                antallFelt.setText(""+res.getInt("quantity"));
                res = setning.executeQuery("select manufacturer from product where product_nr = "+chosenProductID);
                res.next();
                produsentFelt.setText(res.getString("manufacturer"));
                db.kobleFra();
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, "Her oppsto det en feil" + e + "");
                db.kobleFra();
            }
        }
        
    }//GEN-LAST:event_editProductButtonActionPerformed

    private void productBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productBackActionPerformed
        editProductWindow.setVisible(false);
        editProductWindow.dispose();
    }//GEN-LAST:event_productBackActionPerformed

    private void storeBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeBackActionPerformed
        editStoreWindow.setVisible(false);
        editStoreWindow.dispose();
    }//GEN-LAST:event_storeBackActionPerformed

    private void deleteProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductButtonActionPerformed
        if(productList.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null,"Du må velge ett produkt fra listen først");
        } 
        else {
            try{
                Statement stmt = db.kobleTil().createStatement();
                String product = productList.getSelectedValue().toString();
                String findId = "Select store_id from store where store_name = '" + storeName +"' ";
                res = stmt.executeQuery(findId);
                res.next();
                int id = res.getInt("Store_id");
                String query ="delete from product where name = '" + product +"' and product.product_nr = (select storelink.product_nr from storelink where storelink.store_id = " +id+")";
                stmt.executeUpdate(query);
                db.kobleFra();
                fyllProdukt();
            }catch(Exception e ){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_deleteProductButtonActionPerformed

    private void regProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regProductButtonActionPerformed
        regProductWindow.setVisible(true);
    }//GEN-LAST:event_regProductButtonActionPerformed

    private void productRegBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productRegBackActionPerformed
        regProductWindow.setVisible(false);
        regProductWindow.dispose();
    }//GEN-LAST:event_productRegBackActionPerformed

    private void regButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regButtonActionPerformed
        int svar = JOptionPane.showConfirmDialog(null, "Have you given values to all variables?", "Have you given values to all variables?", JOptionPane.YES_NO_OPTION);
        if(svar == JOptionPane.YES_OPTION){
            try{
                String navn = regProductName.getText();
                String beskrivelse = regProductDescription.getText();
                double pris = Double.parseDouble(regProductPrice.getText());
                int antall = Integer.parseInt(regProductQuantity.getText());
                String produsent = regProductManufacturer.getText();
                Statement setning = db.kobleTil().createStatement();
                String insert = "insert into product ( name, description, price, quantity, manufacturer) values('"+navn+ "', '" +beskrivelse+ "', " +pris+", " +antall+", '" +produsent+"')";
                setning.executeUpdate(insert);
                res = setning.executeQuery("select store_ID from store where owner_id = "+id+"");
                res.next();
                int storeID = res.getInt("store_ID");
                res = setning.executeQuery("select product_nr from product where name = '"+navn+"'");
                res.next();
                int nr = res.getInt("product_nr");
                setning.executeUpdate("insert into storelink values (" +nr+ ", " +storeID+")");
                fyllProdukt();
                db.kobleFra();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Her oppsto det en feil" + e + "");

                db.kobleFra();
            }
        }else {
            JOptionPane.showMessageDialog(null,"Fill all of them out first");
        }
    }//GEN-LAST:event_regButtonActionPerformed

    private void productSelected(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productSelected
        editProductButton.setEnabled(true);
        deleteProductButton.setEnabled(true);
    }//GEN-LAST:event_productSelected

    private void saveProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProductButtonActionPerformed
        try{
            String nyttNavn = navneFelt.getText();
            String nyBeskrivelse = beskrivelse.getText();
            double nyPris = Double.parseDouble(prisFelt.getText());
            int nyAntall = Integer.parseInt(antallFelt.getText());
            String nyProdusent = produsentFelt.getText();
            
            Statement setning = db.kobleTil().createStatement();

            setning.executeUpdate("update product set name = '"+nyttNavn+"' where product_nr = "+chosenProductID);
            setning.executeUpdate("update product set description = '"+nyBeskrivelse+"' where product_nr = "+chosenProductID);
            setning.executeUpdate("update product set price = "+nyPris+" where product_nr = "+chosenProductID);
            setning.executeUpdate("update product set quantity = "+nyAntall+" where product_nr = "+chosenProductID);
            setning.executeUpdate("update product set manufacturer = '"+nyProdusent+"' where product_nr = "+chosenProductID);
            db.kobleFra();
            fyllStoreInfo();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Her oppsto det en feil" + e + "");
            db.kobleFra();
        }
    }//GEN-LAST:event_saveProductButtonActionPerformed

    private void saveStoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveStoreButtonActionPerformed
        try{
            String nyttNavn = storeNameField.getText();
            String nyType = storeTypeField.getText();
            double nyTurnover = Double.parseDouble(turnoverField.getText());
            String nyBygning = buildingField.getText();
            int nyEtg = Integer.parseInt(floorField.getText());
            
            Statement setning = db.kobleTil().createStatement();
            
            storeName = nyttNavn;
            endreNavn(nyttNavn);

            setning.executeUpdate("update store set store_name = '"+nyttNavn+"' where owner_id = "+id+"");
            setning.executeUpdate("update store set store_type = '"+nyType+"' where owner_id = "+id+"");
            setning.executeUpdate("update store set turnover = "+nyTurnover+" where owner_id = "+id+"");
            setning.executeUpdate("update store set building = '"+nyBygning+"' where owner_id = "+id+"");
            setning.executeUpdate("update store set floor = "+nyEtg+" where owner_id = "+id+"");
            db.kobleFra();
            fyllStoreInfo();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Her oppsto det en feil" + e + "");
            db.kobleFra();
        }
    }//GEN-LAST:event_saveStoreButtonActionPerformed

    private void endreNavn(String name){
        Name.setText(name);
    }
    
    private void fyllProdukt(){
        try{
            DefaultListModel DLM = new DefaultListModel();
            productList.setModel(DLM);
            Statement setning = db.kobleTil().createStatement();
            res = setning.executeQuery("select name, product.product_nr from product join storelink on product.PRODUCT_NR = storelink.product_nr join store on store.owner_id = "+id+" and store.STORE_ID = storelink.store_ID");
            productIDs.clear();
            //select product_nr from product JOIN storelink ON (product.product_nr = storelink.product_nr)
            while(res.next()) {
                String navn = res.getString("name");
                productIDs.add(res.getInt("product_nr"));
                DLM.addElement(navn);
            }
            productList.setModel(DLM);         
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Her oppsto det en feil 1" + e + "");
        } finally {
            db.kobleFra();  
    }
        
    }
    
    public void fyllStoreInfo(){
        try{
                String info = "Navn: "+(storeName) +"\n";
                Statement setning = db.kobleTil().createStatement();
                res = setning.executeQuery("select store_type from store where owner_id = "+id+"" );
                res.next();
                info+= "Store type: " +(res.getString("store_type")) + "\n";
                res = setning.executeQuery("select turnover from store where owner_id = "+id+"" );
                res.next();
                info += "Anuall turnover: "+(""+res.getDouble("turnover"))+ "\n";
                res = setning.executeQuery("select building from store where owner_id = "+id+"" );
                res.next();
                info += "Building: " +(res.getString("building")) + "\n";
                res = setning.executeQuery("select floor from store where owner_id = "+id+"" );
                res.next();
                info += "Floor: "+(""+res.getInt("floor"));
                storeInfo.setText(info);
                db.kobleFra();
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, "Her oppsto det en feil 2" + e + "");
                db.kobleFra();
            }
    }
   
    /**
     * @param args the command line arguments
     */
    public void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StoreOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StoreOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StoreOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StoreOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JTextField antallFelt;
    private javax.swing.JTextField beskrivelse;
    private javax.swing.JTextField buildingField;
    private javax.swing.JButton deleteProductButton;
    private javax.swing.JButton editProductButton;
    private javax.swing.JFrame editProductWindow;
    private javax.swing.JButton editStoreButton;
    private javax.swing.JFrame editStoreWindow;
    private javax.swing.JTextField floorField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField navneFelt;
    private javax.swing.JTextField prisFelt;
    private javax.swing.JButton productBack;
    private javax.swing.JList productList;
    private javax.swing.JButton productRegBack;
    private javax.swing.JTextField produsentFelt;
    private javax.swing.JButton regButton;
    private javax.swing.JButton regProductButton;
    private javax.swing.JTextField regProductDescription;
    private javax.swing.JTextField regProductManufacturer;
    private javax.swing.JTextField regProductName;
    private javax.swing.JTextField regProductPrice;
    private javax.swing.JTextField regProductQuantity;
    private javax.swing.JFrame regProductWindow;
    private javax.swing.JButton saveProductButton;
    private javax.swing.JButton saveStoreButton;
    private javax.swing.JButton storeBack;
    private javax.swing.JTextArea storeInfo;
    private javax.swing.JTextField storeNameField;
    private javax.swing.JTextField storeTypeField;
    private javax.swing.JTextField turnoverField;
    // End of variables declaration//GEN-END:variables
}
