/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package skoleprosjekt;

import Kode.Database;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Eirik Saur
 */
public class StoreOwner extends javax.swing.JFrame {
    private String storeName;
    private String username;
    private ResultSet res;
    private Database db = new Database();
    /**
     * Creates new form StoreOwner
     */
    public StoreOwner(String username) {
        try{
        this.username = username;
        Statement setning = db.kobleTil().createStatement();
        res = setning.executeQuery("select owner_id from storeowner where username = '"+username+"'" );
        res.next();
        int x = res.getInt("owner_id");
        res = setning.executeQuery("select store_name from store where store_id = "+x+"");
        res.next();
        storeName = res.getString("store_name");
        initComponents();
        endreNavn();
        fyllProdukt();
        fyllStoreInfo();
        db.kobleFra();
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Her oppsto det en feil" + e + "");
            db.kobleFra();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editProductWindow = new javax.swing.JFrame();
        productBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        navneFelt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        beskrivelse = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        prisFelt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        antallFelt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        produsentFelt = new javax.swing.JTextField();
        saveProductName = new javax.swing.JButton();
        saveProductDescription = new javax.swing.JButton();
        saveProductPrice = new javax.swing.JButton();
        saveProductQuantity = new javax.swing.JButton();
        saveProductManufacturer = new javax.swing.JButton();
        regButton = new javax.swing.JButton();
        editStoreWindow = new javax.swing.JFrame();
        storeBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        storeTypeField = new javax.swing.JTextField();
        turnoverField = new javax.swing.JTextField();
        buildingField = new javax.swing.JTextField();
        floorField = new javax.swing.JTextField();
        storeNameField = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        editStoreButton = new javax.swing.JButton();
        editProductButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        productList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        storeInfo = new javax.swing.JTextArea();
        Name = new javax.swing.JLabel();
        deleteProductButton = new javax.swing.JButton();
        regProductButton = new javax.swing.JButton();

        editProductWindow.setMinimumSize(new java.awt.Dimension(700, 300));

        productBack.setText("Back");
        productBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productBackActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        navneFelt.setText("jTextField1");
        navneFelt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navneFeltActionPerformed(evt);
            }
        });

        jLabel3.setText("Description");

        beskrivelse.setText("jTextField1");
        beskrivelse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beskrivelseActionPerformed(evt);
            }
        });

        jLabel4.setText("Price");

        prisFelt.setText("jTextField1");
        prisFelt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prisFeltActionPerformed(evt);
            }
        });

        jLabel5.setText("Quantity");

        antallFelt.setText("jTextField1");
        antallFelt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antallFeltActionPerformed(evt);
            }
        });

        jLabel6.setText("Manufacturer");

        produsentFelt.setText("jTextField1");
        produsentFelt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produsentFeltActionPerformed(evt);
            }
        });

        saveProductName.setBackground(new java.awt.Color(51, 153, 0));
        saveProductName.setText("Save");
        saveProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProductNameActionPerformed(evt);
            }
        });

        saveProductDescription.setBackground(new java.awt.Color(51, 153, 0));
        saveProductDescription.setText("Save");
        saveProductDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProductDescriptionActionPerformed(evt);
            }
        });

        saveProductPrice.setBackground(new java.awt.Color(51, 153, 0));
        saveProductPrice.setText("Save");
        saveProductPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProductPriceActionPerformed(evt);
            }
        });

        saveProductQuantity.setBackground(new java.awt.Color(51, 153, 0));
        saveProductQuantity.setText("Save");
        saveProductQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProductQuantityActionPerformed(evt);
            }
        });

        saveProductManufacturer.setBackground(new java.awt.Color(51, 153, 0));
        saveProductManufacturer.setText("Save");
        saveProductManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProductManufacturerActionPerformed(evt);
            }
        });

        regButton.setText("Reg new product");

        javax.swing.GroupLayout editProductWindowLayout = new javax.swing.GroupLayout(editProductWindow.getContentPane());
        editProductWindow.getContentPane().setLayout(editProductWindowLayout);
        editProductWindowLayout.setHorizontalGroup(
            editProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editProductWindowLayout.createSequentialGroup()
                .addComponent(productBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(regButton)
                .addContainerGap())
            .addGroup(editProductWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editProductWindowLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(produsentFelt, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveProductManufacturer))
                    .addGroup(editProductWindowLayout.createSequentialGroup()
                        .addGroup(editProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(editProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(editProductWindowLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(editProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(editProductWindowLayout.createSequentialGroup()
                                        .addComponent(prisFelt, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(saveProductPrice))
                                    .addGroup(editProductWindowLayout.createSequentialGroup()
                                        .addComponent(antallFelt, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(saveProductQuantity)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(editProductWindowLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(editProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(editProductWindowLayout.createSequentialGroup()
                                        .addComponent(navneFelt, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(saveProductName))
                                    .addGroup(editProductWindowLayout.createSequentialGroup()
                                        .addComponent(beskrivelse, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(saveProductDescription)))))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        editProductWindowLayout.setVerticalGroup(
            editProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editProductWindowLayout.createSequentialGroup()
                .addGroup(editProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productBack)
                    .addGroup(editProductWindowLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(regButton)))
                .addGap(18, 18, 18)
                .addGroup(editProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(navneFelt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveProductName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(beskrivelse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveProductDescription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(prisFelt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveProductPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(antallFelt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(saveProductQuantity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(produsentFelt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveProductManufacturer)))
        );

        editStoreWindow.setMinimumSize(new java.awt.Dimension(550, 300));

        storeBack.setText("Back");
        storeBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeBackActionPerformed(evt);
            }
        });

        jLabel7.setText("Store name");

        jLabel8.setText("Store type");

        jLabel9.setText("Turnover");

        jLabel10.setText("Building");

        jLabel11.setText("Floor");

        storeTypeField.setText("jTextField6");
        storeTypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeTypeFieldActionPerformed(evt);
            }
        });

        turnoverField.setText("jTextField6");

        buildingField.setText("jTextField6");

        floorField.setText("jTextField6");

        storeNameField.setText("jTextField6");

        jButton10.setText("Edit");

        jButton11.setText("Edit");

        jButton12.setText("Edit");

        jButton13.setText("Edit");

        jButton14.setText("Edit");

        javax.swing.GroupLayout editStoreWindowLayout = new javax.swing.GroupLayout(editStoreWindow.getContentPane());
        editStoreWindow.getContentPane().setLayout(editStoreWindowLayout);
        editStoreWindowLayout.setHorizontalGroup(
            editStoreWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editStoreWindowLayout.createSequentialGroup()
                .addComponent(storeBack)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(editStoreWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editStoreWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(editStoreWindowLayout.createSequentialGroup()
                        .addGroup(editStoreWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addGroup(editStoreWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editStoreWindowLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(storeNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(editStoreWindowLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(buildingField, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(editStoreWindowLayout.createSequentialGroup()
                        .addGroup(editStoreWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(editStoreWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(storeTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(turnoverField, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editStoreWindowLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(floorField, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(editStoreWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton12)
                    .addComponent(jButton13)
                    .addComponent(jButton14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        editStoreWindowLayout.setVerticalGroup(
            editStoreWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editStoreWindowLayout.createSequentialGroup()
                .addComponent(storeBack)
                .addGap(18, 18, 18)
                .addGroup(editStoreWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(storeNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10))
                .addGap(18, 18, 18)
                .addGroup(editStoreWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jButton11)
                    .addComponent(storeTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(editStoreWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(turnoverField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14)
                    .addComponent(jLabel9))
                .addGap(12, 12, 12)
                .addGroup(editStoreWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buildingField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editStoreWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(floorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jButton13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editStoreButton.setText("Edit store info");
        editStoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStoreButtonActionPerformed(evt);
            }
        });

        editProductButton.setText("Edit product");
        editProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProductButtonActionPerformed(evt);
            }
        });

        productList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(productList);

        storeInfo.setColumns(20);
        storeInfo.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        storeInfo.setRows(5);
        jScrollPane2.setViewportView(storeInfo);

        Name.setFont(new java.awt.Font("sansserif", 3, 36)); // NOI18N
        Name.setText("NAVN PÅ BUTIKK");

        deleteProductButton.setText("Delete product");
        deleteProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductButtonActionPerformed(evt);
            }
        });

        regProductButton.setText("Reg product");
        regProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regProductButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editStoreButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(regProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(regProductButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteProductButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editProductButton)
                            .addComponent(editStoreButton)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beskrivelseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beskrivelseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beskrivelseActionPerformed

    private void prisFeltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prisFeltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prisFeltActionPerformed

    private void antallFeltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antallFeltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_antallFeltActionPerformed

    private void produsentFeltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produsentFeltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produsentFeltActionPerformed

    private void navneFeltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navneFeltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_navneFeltActionPerformed

    private void storeTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeTypeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_storeTypeFieldActionPerformed

    private void editStoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStoreButtonActionPerformed
            editStoreWindow.setVisible(true);
            try{
                storeNameField.setText(storeName);
                Statement setning = db.kobleTil().createStatement();
                res = setning.executeQuery("select store_type from store where store_name = '"+storeName+"'" );
                res.next();
                storeTypeField.setText(res.getString("store_type"));
                res = setning.executeQuery("select turnover from store where store_name = '"+storeName+"'" );
                res.next();
                turnoverField.setText(""+res.getDouble("turnover"));
                res = setning.executeQuery("select building from store where store_name = '"+storeName+"'" );
                res.next();
                buildingField.setText(res.getString("building"));
                res = setning.executeQuery("select floor from store where store_name = '"+storeName+"'" );
                res.next();
                floorField.setText(""+res.getInt("floor"));
                db.kobleFra();
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, "Her oppsto det en feil" + e + "");
                db.kobleFra();
            }
    }//GEN-LAST:event_editStoreButtonActionPerformed

    private void editProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProductButtonActionPerformed
        if(productList.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null,"Du må velge ett produkt fra listen først");
        } 
        else {
        editProductWindow.setVisible(true);
        try{
            navneFelt.setText(productList.getSelectedValue().toString());
            Statement setning = db.kobleTil().createStatement();
            res = setning.executeQuery("select description from product where name = '"+productList.getSelectedValue().toString()+"'" );
            res.next();
            beskrivelse.setText(res.getString("description"));
            res = setning.executeQuery("select price from product where name = '"+productList.getSelectedValue().toString()+"'" );
            res.next();
            prisFelt.setText(""+res.getInt("price"));
            res = setning.executeQuery("select quantity from product where name = '"+productList.getSelectedValue().toString()+"'" );
            res.next();
            antallFelt.setText(""+res.getInt("quantity"));
            res = setning.executeQuery("select manufacturer from product where name = '"+productList.getSelectedValue().toString()+"'" );
            res.next();
            produsentFelt.setText(res.getString("manufacturer"));
            db.kobleFra();
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Her oppsto det en feil" + e + "");
            db.kobleFra();
        }
        }
        
    }//GEN-LAST:event_editProductButtonActionPerformed

    private void productBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productBackActionPerformed
        editProductWindow.setVisible(false);
        editProductWindow.dispose();
    }//GEN-LAST:event_productBackActionPerformed

    private void storeBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeBackActionPerformed
        editStoreWindow.setVisible(false);
        editStoreWindow.dispose();
    }//GEN-LAST:event_storeBackActionPerformed

    private void deleteProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductButtonActionPerformed
        if(productList.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null,"Du må velge ett produkt fra listen først");
        } 
        else {
        //Lag metode for sletting av produkt.
        }
    }//GEN-LAST:event_deleteProductButtonActionPerformed

    private void regProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regProductButtonActionPerformed
        editProductWindow.setVisible(true);
    }//GEN-LAST:event_regProductButtonActionPerformed

    private void saveProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProductNameActionPerformed
        try{
        String nyttNavn = navneFelt.getText();
        Statement setning = db.kobleTil().createStatement();
        setning.executeUpdate("update product set name = '"+nyttNavn+"' where name = '"+productList.getSelectedValue().toString() +"'");
        fyllProdukt();
        db.kobleFra();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Her oppsto det en feil" + e + "");
            db.kobleFra();
        }
    }//GEN-LAST:event_saveProductNameActionPerformed

    private void saveProductDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProductDescriptionActionPerformed
        try{
        String nyBeskrivelse = beskrivelse.getText();
        Statement setning = db.kobleTil().createStatement();
        setning.executeUpdate("update product set description = '"+nyBeskrivelse+"' where name = '"+productList.getSelectedValue().toString() +"'");
        fyllProdukt();
        db.kobleFra();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Her oppsto det en feil" + e + "");
            db.kobleFra();
        }
    }//GEN-LAST:event_saveProductDescriptionActionPerformed

    private void saveProductPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProductPriceActionPerformed
        try{
        double nyPris = Double.parseDouble(prisFelt.getText());
        Statement setning = db.kobleTil().createStatement();
        setning.executeUpdate("update product set price = "+nyPris+" where name = '"+productList.getSelectedValue().toString() +"'");
        fyllProdukt();
        db.kobleFra();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Her oppsto det en feil" + e + "");
            db.kobleFra();
        }
    }//GEN-LAST:event_saveProductPriceActionPerformed

    private void saveProductQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProductQuantityActionPerformed
        try{
        int nyttAntall = Integer.parseInt(antallFelt.getText());
        Statement setning = db.kobleTil().createStatement();
        setning.executeUpdate("update product set quantity = "+nyttAntall+" where name = '"+productList.getSelectedValue().toString() +"'");
        fyllProdukt();
        db.kobleFra();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Her oppsto det en feil" + e + "");
            db.kobleFra();
        }
    }//GEN-LAST:event_saveProductQuantityActionPerformed

    private void saveProductManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProductManufacturerActionPerformed
        try{
        String nyProdusent = produsentFelt.getText();
        Statement setning = db.kobleTil().createStatement();
        setning.executeUpdate("update product set manufacturer = '"+nyProdusent+"' where name = '"+productList.getSelectedValue().toString() +"'");
        fyllProdukt();
        db.kobleFra();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Her oppsto det en feil" + e + "");
            db.kobleFra();
        }
    }//GEN-LAST:event_saveProductManufacturerActionPerformed

    private void endreNavn(){
        Name.setText(storeName);
    }
    
    private void fyllProdukt(){
        try{
            DefaultListModel DLM = new DefaultListModel();
            productList.setModel(DLM);
            Statement setning = db.kobleTil().createStatement();
            res = setning.executeQuery("select product_nr from store JOIN storelink ON"
                    + "(store.store_id = storelink.store_id)"
                    + "WHERE store_name = '"+ storeName + "'");
            
            //select product_nr from product JOIN storelink ON (product.product_nr = storelink.product_nr)
            if(res.next()) {
                int productID = res.getInt("product_nr");
                res = setning.executeQuery("select name from product where product_nr = "+productID+"");
                while (res.next()) {
                    String navn = res.getString("name");
                    DLM.addElement(navn);
                }
                productList.setModel(DLM);
                db.kobleFra();
            }
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Her oppsto det en feil" + e + "");
            db.kobleFra();
        }
    }
    
    public void fyllStoreInfo(){
        try{
                String info = "Navn: "+(storeName) +"\n";
                Statement setning = db.kobleTil().createStatement();
                res = setning.executeQuery("select store_type from store where store_name = '"+storeName+"'" );
                res.next();
                info+= "Store type: " +(res.getString("store_type")) + "\n";
                res = setning.executeQuery("select turnover from store where store_name = '"+storeName+"'" );
                res.next();
                info += "Anuall turnover: "+(""+res.getDouble("turnover"))+ "\n";
                res = setning.executeQuery("select building from store where store_name = '"+storeName+"'" );
                res.next();
                info += "Building: " +(res.getString("building")) + "\n";
                res = setning.executeQuery("select floor from store where store_name = '"+storeName+"'" );
                res.next();
                info += "Floor: "+(""+res.getInt("floor"));
                storeInfo.setText(info);
                db.kobleFra();
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, "Her oppsto det en feil" + e + "");
                db.kobleFra();
            }
    }
    /**
     * @param args the command line arguments
     */
    public void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StoreOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StoreOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StoreOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StoreOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StoreOwner(username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JTextField antallFelt;
    private javax.swing.JTextField beskrivelse;
    private javax.swing.JTextField buildingField;
    private javax.swing.JButton deleteProductButton;
    private javax.swing.JButton editProductButton;
    private javax.swing.JFrame editProductWindow;
    private javax.swing.JButton editStoreButton;
    private javax.swing.JFrame editStoreWindow;
    private javax.swing.JTextField floorField;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField navneFelt;
    private javax.swing.JTextField prisFelt;
    private javax.swing.JButton productBack;
    private javax.swing.JList productList;
    private javax.swing.JTextField produsentFelt;
    private javax.swing.JButton regButton;
    private javax.swing.JButton regProductButton;
    private javax.swing.JButton saveProductDescription;
    private javax.swing.JButton saveProductManufacturer;
    private javax.swing.JButton saveProductName;
    private javax.swing.JButton saveProductPrice;
    private javax.swing.JButton saveProductQuantity;
    private javax.swing.JButton storeBack;
    private javax.swing.JTextArea storeInfo;
    private javax.swing.JTextField storeNameField;
    private javax.swing.JTextField storeTypeField;
    private javax.swing.JTextField turnoverField;
    // End of variables declaration//GEN-END:variables
}
